### ISSUE TITLE
add docker image build schedule to actions

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/docker-backup#14]
**Issue description**:

Currently the docker image is only built on push. Changes in the docker-wikibase image are therefore only incorporated when there are pushes to docker-backup, which can lead to errors.
 
**TODOS**: 

- [ ] add `schedule: cron: ...` to actions workflow file for e.g. daily updates, as already done for docker-wikibase https://github.com/MaRDI4NFDI/docker-wikibase/blob/d289885f96a558d440d8e9d0f0355f5eef52c310/.github/workflows/main.yml#L8

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed

**Comment by dajuno** [comment]
Note: cronjob for docker-wikibase is set at 0:00, [d15660d](https://github.com/MaRDI4NFDI/docker-backup/commit/d15660df05811e279695d97b54b3e2ab6c997608) sets up cronjob for 0:10, such that possible changes in docker-wikibase are taken into account

**Comment by dajuno** [comment]
closed by [f187821](https://github.com/MaRDI4NFDI/docker-backup/commit/f18782130fc4a2821ce8dd8961d331d8cd560901)
